packages:
  - integration-tests
  - mcp-servers/*
  - monitor
  - packages/*
  - tests/*
  - website

catalog:
  '@biomejs/biome': ^2.1.2
  '@enkaku/async': ^0.12.2
  '@enkaku/client': ^0.12.0
  '@enkaku/event': ^0.12.1
  '@enkaku/generator': ^0.12.1
  '@enkaku/http-client-transport': ^0.12.0
  '@enkaku/http-server-transport': ^0.12.0
  '@enkaku/node-streams-transport': ^0.12.1
  '@enkaku/protocol': ^0.12.0
  '@enkaku/schema': ^0.12.0
  '@enkaku/server': ^0.12.0
  '@enkaku/socket-transport': ^0.12.1
  '@enkaku/stream': ^0.12.4
  '@enkaku/transport': ^0.12.0
  '@hono/node-server': ^1.17.0
  '@jest/globals': ^30.0.4
  '@mantine/core': ^8.1.3
  '@mantine/hooks': ^8.1.3
  '@oclif/core': ^4.5.1
  '@oclif/plugin-help': ^6.2.31
  '@oclif/plugin-plugins': ^5.4.45
  '@oclif/test': ^4.1.13
  '@swc/cli': ^0.7.8
  '@swc/core': ^1.13.0
  '@swc/jest': ^0.2.39
  '@tabler/icons-react': ^3.34.0
  '@tanstack/react-router': ^1.128.4
  '@tanstack/react-virtual': ^3.13.9
  '@tanstack/router-devtools': ^1.128.4
  '@tanstack/router-plugin': ^1.128.4
  '@types/jest': ^30.0.0
  '@types/luxon': ^3.6.2
  '@types/node': ^24.0.15
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.6
  '@types/turndown': ^5.0.5
  '@vitejs/plugin-react-swc': ^3.11.0
  ansi-colors: ^4.1.3
  del-cli: ^6.0.0
  enquirer: ^2.4.1
  eventsource-parser: ^3.0.2
  get-port: ^7.1.0
  globals: ^16.3.0
  hono: ^4.8.5
  jest: ^30.0.4
  jotai: ^2.12.5
  ky: ^1.8.2
  luxon: ^3.7.1
  nano-spawn: ^1.0.2
  oclif: ^4.21.0
  ora: ^8.2.0
  postcss: ^8.5.6
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  prism-react-renderer: ^2.3.0
  react: ^19.1.0
  react-dom: ^19.1.0
  tsx: ^4.19.4
  turbo: ^2.5.5
  turndown: ^7.2.0
  turndown-plugin-gfm: ^1.0.2
  typedoc: ^0.28.7
  typedoc-plugin-markdown: ^4.7.0
  vite: ^7.0.5
  vite-bundle-analyzer: ^1.1.0

catalogMode: manual

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - unrs-resolver
  - yarn

overrides:
  css-select: 5.2.0
