packages:
  - integration-tests
  - mcp-servers/*
  - monitor
  - packages/*
  - tests/*
  - website

catalog:
  '@biomejs/biome': ^2.3.13
  '@enkaku/async': ^0.12.2
  '@enkaku/client': ^0.12.4
  '@enkaku/event': ^0.12.1
  '@enkaku/generator': ^0.12.1
  '@enkaku/http-client-transport': ^0.12.0
  '@enkaku/http-server-transport': ^0.12.2
  '@enkaku/node-streams-transport': ^0.12.1
  '@enkaku/protocol': ^0.12.1
  '@enkaku/schema': ^0.12.1
  '@enkaku/server': ^0.12.3
  '@enkaku/socket-transport': ^0.12.1
  '@enkaku/stream': ^0.12.4
  '@enkaku/transport': ^0.12.0
  '@hono/node-server': ^1.19.9
  '@mantine/core': ^8.3.13
  '@mantine/hooks': ^8.3.13
  '@oclif/core': ^4.8.0
  '@oclif/plugin-help': ^6.2.37
  '@oclif/plugin-plugins': ^5.4.55
  '@oclif/test': ^4.1.16
  '@swc/cli': ^0.7.10
  '@swc/core': ^1.15.11
  '@tabler/icons-react': ^3.36.1
  '@tanstack/react-router': ^1.157.16
  '@tanstack/react-virtual': ^3.13.18
  '@tanstack/router-devtools': ^1.157.16
  '@tanstack/router-plugin': ^1.157.16
  '@types/luxon': ^3.7.1
  '@types/node': ^25.1.0
  '@types/react': ^19.2.10
  '@types/react-dom': ^19.2.3
  '@types/turndown': ^5.0.6
  '@vitejs/plugin-react-swc': ^4.2.2
  '@vitest/ui': ^4.0.18
  ansi-colors: ^4.1.3
  del-cli: ^7.0.0
  enquirer: ^2.4.1
  eventsource-parser: ^3.0.6
  get-port: ^7.1.0
  globals: ^17.2.0
  hono: ^4.11.7
  jotai: ^2.17.0
  ky: ^1.14.3
  luxon: ^3.7.2
  nano-spawn: ^2.0.0
  oclif: ^4.22.70
  ora: ^9.1.0
  postcss: ^8.5.6
  postcss-preset-mantine: ^1.18.0
  postcss-simple-vars: ^7.0.1
  prism-react-renderer: ^2.3.0
  react: ^19.2.4
  react-dom: ^19.2.4
  tsx: ^4.21.0
  turbo: ^2.8.0
  turndown: ^7.2.2
  turndown-plugin-gfm: ^1.0.2
  typedoc: ^0.28.16
  typedoc-plugin-markdown: ^4.9.0
  vite: ^7.3.1
  vite-bundle-analyzer: ^1.3.2
  vitest: ^4.0.18

catalogMode: manual

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - unrs-resolver
  - yarn

overrides:
  css-select: 5.2.0
