/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlowsRouteImport } from './routes/flows'
import { Route as TracesRouteImport } from './routes/traces'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as InboxItemIDRouteImport } from './routes/inbox.$itemID'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIDRouteImport } from './routes/runs.$runID'
import { Route as TracesTraceIDRouteImport } from './routes/traces.$traceID'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsRoute = FlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesRoute = TracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxItemIDRoute = InboxItemIDRouteImport.update({
  id: '/inbox/$itemID',
  path: '/inbox/$itemID',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIDRoute = RunsRunIDRouteImport.update({
  id: '/runs/$runID',
  path: '/runs/$runID',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesTraceIDRoute = TracesTraceIDRouteImport.update({
  id: '/$traceID',
  path: '/$traceID',
  getParentRoute: () => TracesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flows': typeof FlowsRoute
  '/traces': typeof TracesRouteWithChildren
  '/inbox/$itemID': typeof InboxItemIDRoute
  '/runs/$runID': typeof RunsRunIDRoute
  '/traces/$traceID': typeof TracesTraceIDRoute
  '/inbox/': typeof InboxIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flows': typeof FlowsRoute
  '/traces': typeof TracesRouteWithChildren
  '/inbox/$itemID': typeof InboxItemIDRoute
  '/runs/$runID': typeof RunsRunIDRoute
  '/traces/$traceID': typeof TracesTraceIDRoute
  '/inbox': typeof InboxIndexRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flows': typeof FlowsRoute
  '/traces': typeof TracesRouteWithChildren
  '/inbox/$itemID': typeof InboxItemIDRoute
  '/runs/$runID': typeof RunsRunIDRoute
  '/traces/$traceID': typeof TracesTraceIDRoute
  '/inbox/': typeof InboxIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flows'
    | '/traces'
    | '/inbox/$itemID'
    | '/runs/$runID'
    | '/traces/$traceID'
    | '/inbox/'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flows'
    | '/traces'
    | '/inbox/$itemID'
    | '/runs/$runID'
    | '/traces/$traceID'
    | '/inbox'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/flows'
    | '/traces'
    | '/inbox/$itemID'
    | '/runs/$runID'
    | '/traces/$traceID'
    | '/inbox/'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlowsRoute: typeof FlowsRoute
  TracesRoute: typeof TracesRouteWithChildren
  InboxItemIDRoute: typeof InboxItemIDRoute
  RunsRunIDRoute: typeof RunsRunIDRoute
  InboxIndexRoute: typeof InboxIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows': {
      id: '/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof FlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces': {
      id: '/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof TracesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$itemID': {
      id: '/inbox/$itemID'
      path: '/inbox/$itemID'
      fullPath: '/inbox/$itemID'
      preLoaderRoute: typeof InboxItemIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runID': {
      id: '/runs/$runID'
      path: '/runs/$runID'
      fullPath: '/runs/$runID'
      preLoaderRoute: typeof RunsRunIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/$traceID': {
      id: '/traces/$traceID'
      path: '/$traceID'
      fullPath: '/traces/$traceID'
      preLoaderRoute: typeof TracesTraceIDRouteImport
      parentRoute: typeof TracesRoute
    }
  }
}

interface TracesRouteChildren {
  TracesTraceIDRoute: typeof TracesTraceIDRoute
}

const TracesRouteChildren: TracesRouteChildren = {
  TracesTraceIDRoute: TracesTraceIDRoute,
}

const TracesRouteWithChildren =
  TracesRoute._addFileChildren(TracesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlowsRoute: FlowsRoute,
  TracesRoute: TracesRouteWithChildren,
  InboxItemIDRoute: InboxItemIDRoute,
  RunsRunIDRoute: RunsRunIDRoute,
  InboxIndexRoute: InboxIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
