/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as InboxItemIDRouteImport } from './routes/inbox.$itemID'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIDRouteImport } from './routes/runs.$runID'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxItemIDRoute = InboxItemIDRouteImport.update({
  id: '/inbox/$itemID',
  path: '/inbox/$itemID',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIDRoute = RunsRunIDRouteImport.update({
  id: '/runs/$runID',
  path: '/runs/$runID',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inbox/$itemID': typeof InboxItemIDRoute
  '/runs/$runID': typeof RunsRunIDRoute
  '/inbox/': typeof InboxIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inbox/$itemID': typeof InboxItemIDRoute
  '/runs/$runID': typeof RunsRunIDRoute
  '/inbox': typeof InboxIndexRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inbox/$itemID': typeof InboxItemIDRoute
  '/runs/$runID': typeof RunsRunIDRoute
  '/inbox/': typeof InboxIndexRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inbox/$itemID' | '/runs/$runID' | '/inbox/' | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inbox/$itemID' | '/runs/$runID' | '/inbox' | '/runs'
  id:
    '__root__' | '/' | '/inbox/$itemID' | '/runs/$runID' | '/inbox/' | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InboxItemIDRoute: typeof InboxItemIDRoute
  RunsRunIDRoute: typeof RunsRunIDRoute
  InboxIndexRoute: typeof InboxIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/inbox'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$itemID': {
      id: '/inbox/$itemID'
      path: '/inbox/$itemID'
      fullPath: '/inbox/$itemID'
      preLoaderRoute: typeof InboxItemIDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runID': {
      id: '/runs/$runID'
      path: '/runs/$runID'
      fullPath: '/runs/$runID'
      preLoaderRoute: typeof RunsRunIDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InboxItemIDRoute: InboxItemIDRoute,
  RunsRunIDRoute: RunsRunIDRoute,
  InboxIndexRoute: InboxIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
